name: totalizer_cart
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  archive: ^4.0.1
  camera: ^0.11.0+2
  cloud_firestore: ^5.4.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  icons_launcher: ^3.0.0
  rflutter_alert: ^2.0.7
  uuid: ^4.5.1
  google_mlkit_barcode_scanning: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
